name: CI
on: [push]
jobs:
  eslint:
    name: Lint code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install
        run: npm clean-install

      - name: Lint
        run: npm run lint
